### ISSUE TITLE
Bug: Get Error When Set City ID 

### ISSUE THREAD

**Issue by NekoSukuriputo** [adityaputra11/sholat-reminder#1]
Assalamualaikum Developer, I found some issue after installing extension, when I want set city id using `CTLR+SHIFT+P` get pop up window error like image below.

![image](https://github.com/user-attachments/assets/150016ae-679d-408a-9a0d-462a1a859e33)

Extension Version : v1.0.4
VSCode Version: 1.95.2

**Comment by lutfialdrii** [comment]
same error on ubuntu 24.0
![image](https://github.com/user-attachments/assets/c4d15c36-7589-4512-af05-b1a1d38dfbf6)

**Comment by adityaputra11** [comment]
[sholat-reminder-1.0.6.vsix.zip](https://github.com/user-attachments/files/17730061/sholat-reminder-1.0.6.vsix.zip)
boleh minta tolong di coba yang versi ini mas mas @NekoSukuriputo @lutfialdrii jika berkenan

**Comment by NekoSukuriputo** [comment]
> [sholat-reminder-1.0.6.vsix.zip](https://github.com/user-attachments/files/17730061/sholat-reminder-1.0.6.vsix.zip) boleh minta tolong di coba yang versi ini mas mas @NekoSukuriputo @lutfialdrii jika berkenan

Fixed bang, GG 👍👍

![image](https://github.com/user-attachments/assets/023cfe29-6908-4cb4-94d2-d8f2365aa04b)
![image](https://github.com/user-attachments/assets/fd54257f-ff37-47e3-9978-700c41892e42)

**Comment by adityaputra11** [comment]
woke mas, selanjutnya update di marketplace

**Comment by adityaputra11** [comment]
Thankssss GG mas rahmat
