### ISSUE TITLE
Add correct time formatting in Status Bar view

### ISSUE THREAD

**Issue by fadhln** [adityaputra11/sholat-reminder#10]
## General Information

- Extension version: `v.1.0.10`
- Visual Studio Cpde version: `1.95.2`

## Issue Description

Right now, the countdown display in VSCode status bar looks like this:

```
Isya(19:05):-1:0:8
```

Screenshot:
<img width="165" alt="SeaTalk_IMG_20241114_180628" src="https://github.com/user-attachments/assets/361488b1-eeb5-4ba4-b440-36fd77a5b068">

It will be better if we follow a Standard Time Format of `HH:mm:ss`, by keeping a two digit number even when the digit hit `<10`. So instead it will show something like this:

```
Isya(19:05):-01:00:08
```

**Comment by adityaputra11** [comment]
Alhamdulillah, thank you for the feedback, i will fixint this

**Comment by fadhln** [comment]
@adityaputra11 I already pushed a PR just now lol, can help take a look 😄
